# CI De Nível 1 - Disparo manual a partir de um clique no botão "Build"

# nome do 'pipeline'
name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:

  e2e-test:
    
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando Dependências
        run: npm install

      - name: Executando Testes Trabalho Final
        run: npm test
